---
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: |
          npm run check && npm run lint
        language: system
        types: [ts]
        pass_filenames: false
