---
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: |
          npm run lint
        language: system
        types: [ts]
        pass_filenames: false

      - id: tsc-check
        name: tsc-check
        entry: |
          npm run check
        language: system
        types: [ts]
        pass_filenames: false
