/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "$CONFIG_CREATE_STATE_IF_NOT_EXISTS_LABEL": {     "en": "Shall target states automatically be created if they do not exist yet?", "de": "Sollen Zielzustände automatisch erstellt werden, wenn diese noch nicht existieren?", "ru": "Будут ли автоматически создаваться целевые состояния, если они еще не существуют?", "pt": "Os estados-alvo serão criados automaticamente se ainda não existirem?", "nl": "Zullen er automatisch doelstaten worden gecreëerd als ze nog niet bestaan?", "fr": "Les États cibles seront-ils automatiquement créés s’ils n’existent pas encore ?", "it": "Gli stati target verranno creati automaticamente se non esistono ancora?", "es": "¿Se crearán automáticamente estados objetivo si aún no existen?", "pl": "Czy stany docelowe powinny zostać utworzone automatycznie, jeśli jeszcze nie istnieją?", "uk": "Чи повинні автоматично створюватися цільові штати, якщо вони ще не існують?", "zh-cn": "如果目标状态尚不存在，是否会自动创建？"},
    "$PANEL_GLOBAL_SETTINGS_LABEL": {                 "en": "Global settings",                                  "de": "Globale Einstellungen",                            "ru": "Глобальные настройки",                             "pt": "Configurações globais",                            "nl": "Algemene instellingen",                            "fr": "Paramètres globaux",                               "it": "Impostazioni globali",                             "es": "Ajustes globales",                                 "pl": "Ustawienia ogólne",                                "uk": "Глобальні налаштування",                           "zh-cn": "全局设置"},
    "$TAB_LIST_HEADER": {                             "en": "Automations",                                      "de": "Automatisierungen",                                "ru": "Автоматизация",                                    "pt": "Automações",                                       "nl": "Automatiseringen",                                 "fr": "Automatisations",                                  "it": "Automazioni",                                      "es": "Automatizaciones",                                 "pl": "Automatyka",                                       "uk": "Автоматизації",                                    "zh-cn": "自动化"},
};