---
name: Release Publishing

'on':
  push:
    branches:
      - main

jobs:
  create_tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.set-release-tag.outputs.version_tag }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Last two commits for salsify/action-detect-and-tag-new-version

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true
          keys-case: bypass

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          tag-template: 'v{VERSION}'
          version-command: |
            node -p 'require("./package.json").version'

      - name: Set release tag
        id: set-release-tag
        # Trigger this step only when a commit on any branch is tagged with a version number
        run: |
          echo "Checking if a new tag is available..."
          if [ -z "${{ steps.check-version.outputs.tag }}" ]; then
            echo "No tag found!"
            echo "Checking if current version is available..."
            if [  ! -z "${{ steps.check-version.outputs.current-version }}" ]; then
              echo "Current version is available!"
              echo "Checking if forcing re-release flag is set..."
              if [[ "${{ github.event.head_commit.message }}" =~ .*"[re-release]".* ]]; then
                echo "Forcing re-release flag is set!"
                echo "Setting version tag ${{ steps.check-version.outputs.current-version }} ..."
                echo "version_tag=${{ steps.check-version.outputs.current-version }}" >> $GITHUB_OUTPUT
              else
                echo "Forcing re-release flag is not set!"
              fi
            else
              echo "Current version is not available!"
            fi
          else
            echo "New tag found: ${{ steps.check-version.outputs.tag }}"
            echo "version_tag=${{ steps.check-version.outputs.tag }}" >> $GITHUB_OUTPUT
          fi

  create_releases:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: create_tag
    if: needs.create_tag.outputs.version_tag != ''
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true
          keys-case: bypass

      - name: Use Node.js ${{ steps.dotenv.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.dotenv.outputs.NODE_VERSION }}

      - name: Install Dependencies
        shell: bash
        run: 'npm ci'

      - name: Build the adapter
        shell: bash
        run: 'npm run build'

      - name: Publish package to npm
        shell: bash
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm whoami
          npm publish ${{ needs.create_tag.outputs.version_tag }}

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.22.0
        with:
          publish: ${{ needs.create_tag.outputs.version_tag != '' }}
          tag: ${{ needs.create_tag.outputs.version_tag }}
          config-name: release_drafting_config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GENERAL_RW }}
#          # When using Sentry for error reporting, Sentry can be informed about new releases
#          # To enable create a API-Token in Sentry (User settings, API keys)
#          # Enter this token as a GitHub secret (with name SENTRY_AUTH_TOKEN) in the repository options
#          # Then uncomment and customize the following block:
#          sentry: true
#          sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          sentry-project: "iobroker-gjsm"
#          sentry-version-prefix: "iobroker.gjsm"
#          sentry-sourcemap-paths: "build/"
#          # If your sentry project is linked to a GitHub repository, you can enable the following option
#          # sentry-github-integration: true
